name: Detect Collisions

on:
  push:
    branches: [master, develop]
    paths:
      - "src/**"
      - ".github/workflows/benchmarks.yml"
  pull_request:
    branches: [master, develop]
    paths:
      - "src/**"
      - ".github/workflows/benchmarks.yml"
  schedule:
    - cron: "0 1 * * 1,3,5"

jobs:
  bench:
    name: "Run Benchmarks"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - uses: actions/checkout@v3

      - name: Setting up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: |
          npm install
          npm run benchmark
