name: check2d-benchmarks

on:
  # Manual run
  workflow_dispatch:

  # Automatic run on push
  push:
    branches: [main]
    paths:
      - 'src/**'
      - '.github/workflows/benchmarks.yml'

  # Automatic run on pull request
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - '.github/workflows/benchmarks.yml'

jobs:
  bench:
    name: 'Check2D Benchmarks'
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Debug info to ensure workflow starts
      - name: Debug Info
        run: |
          echo "Workflow started"
          echo "Event name: ${{ github.event_name }}"
          pwd
          ls -la

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build
        run: npm run build

      # Run benchmarks
      - name: Run Benchmarks
        run: npm run benchmark
